inherit_from:
  - .rubocop_ruby.yml
  - .rubocop_rails.yml

AllCops:
  TargetRubyVersion: 3.1
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "**/*.ru"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - "node_modules/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "spec/decidim_dummy_app/**/*"
    - "development_app/**/*"

RSpec/DescribeClass:
  Exclude:
    - spec/system/*